SELECT
    I.ITEM_CODE AS CODE,
    CASE
        WHEN IH.ITEM_NAME IS NULL OR I.ITEM_NAME != IH.ITEM_NAME THEN I.ITEM_NAME
        ELSE NULL
    END AS NAME
FROM
    ITEM I
    LEFT OUTER JOIN ITEM_HISTORY IH
    ON I.ITEM_CODE = IH.ITEM_CODE
ORDER BY CODE DESC;
