SELECT
    SALES.SALES_DATE AS SAL_DATE,
    SALES.SALES_NO AS NO,
    DTL.ITEM_CODE AS ITEM_CODE,
    DTL.SALES_QTY AS SAL_QTY,
    DTL.DELIVERED_QTY AS DEL_QTY,
    CASE
        WHEN DTL.DELIVERED_QTY = 0 THEN '未出荷'
        WHEN DTL.DELIVERED_QTY > 0 AND DTL.SALES_QTY > DTL.DELIVERED_QTY THEN '一部出荷'
        WHEN DTL.SALES_QTY = DTL.DELIVERED_QTY THEN '出荷済'
    END AS SHIP_STS
FROM
    SALES
    INNER JOIN SALES_DTL DTL
        ON SALES.SALES_NO = DTL.SALES_NO
        AND SALES.SALES_DATE BETWEEN '2024-04-01' AND '2024-04-10'
ORDER BY
    SAL_DATE DESC,
    NO,
    ITEM_CODE;
