SELECT
    ORDER_NO AS OD_NO,
    SLIP_COMMENT AS COMMENT,
    SUM(LENGTH(SLIP_COMMENT)-LENGTH(REPLACE(SLIP_COMMENT, ',','')))+1 AS CNT
FROM ORDERS
GROUP BY OD_NO
ORDER BY
    CNT DESC,
    OD_NO DESC;
