UPDATE SKU
SET
    STD_COST_PRICE = (
        SELECT STD_COST_PRICE
        FROM GOODS
        WHERE GOODS.GOODS_CODE = SKU.GOODS_CODE
    ),
    UPDATE_USER_NAME = 'MODIFY',
    USER_UPDATE_DATETIME = '2024-08-31 00:00:00'
WHERE SKU_CODE IN (
    SELECT a.SKU_CODE
    FROM SKU a
    JOIN (
        SELECT
            GOODS_CODE,
            ROUND(AVG(STD_COST_PRICE), 1) AS av
        FROM SKU
        GROUP BY GOODS_CODE
    ) b
    ON a.GOODS_CODE = b.GOODS_CODE
    WHERE a.STD_COST_PRICE < b.av
);